Added tests.
Nick13Zen/Nikita_Zenchik pull request #7
Opened 2016-10-31 09:07 UTC by Nick13Zen

2016-10-31 09:52 UTC, AlexanderSoroka requested changes
I have to stop review on this - FileReaderTest.
Re-work and avoid file i/o in tests.

2016-10-31 09:52 UTC, AlexanderSoroka commented on Homework_11/src/main/java/tat/maven/Bicycle.java
> +    private double x = 0.0, y = 0.0;
two fields - two lines

2016-10-31 09:52 UTC, AlexanderSoroka commented on Homework_11/src/main/java/tat/maven/Bicycle.java
> +
useless blank lines

2016-10-31 09:52 UTC, AlexanderSoroka commented on Homework_11/src/main/java/tat/maven/Bicycle.java
> +        return (int) (travelTime) + " hours "
Return time as class or numeric values

2016-10-31 09:52 UTC, AlexanderSoroka commented on Homework_11/src/test/java/test/java/BusTest.java
> +        System.out.println(bus.getTime());
Please remove debug code

2016-10-31 09:52 UTC, AlexanderSoroka commented on Homework_11/src/test/java/test/java/BusTest.java
> +        assertTrue(bus.getTime().equals("0 hours 0 minutes"));
It's very inconvenient to get Time result as String. If I want to use your class and need to get time in seconds I'll have to parse it. In that case I'll just drop your code and find some other

2016-11-02 09:49 UTC, IgorKheidorov commented on Homework_11/src/testng/BicycleTest.java
> +                {2, 0, 2},
Line 19 and 20 is the same equivalence class, you have to set positive, negative and zero values in different combinations

2016-11-02 09:54 UTC, IgorKheidorov commented on Homework_11/src/test/java/test/java/OnfootTest.java
> +        assertTrue(onfoot.getTime() == 0);
1. This test checks nothing (only that trivial getter works well, you have not to test it)
2.  At any case, use assertEquals instead of assertTrue

2016-11-02 09:58 UTC, IgorKheidorov commented on Homework_11/src/testng/BicycleTest.java
> +                {Double.NaN, Double.NaN, 9},
lines 21,22,23 : Values for nagitive tests but used is positive test, will never pass

2016-11-02 09:59 UTC, IgorKheidorov commented on Homework_11/src/testng/BusTest.java
> +                {Double.NaN, Double.NaN, 9},
The same as for Bicycle

2016-11-02 10:01 UTC, IgorKheidorov commented on Homework_11/src/testng/OnfootTest.java
> +                {Double.NaN, Double.NaN, 9},
the same remarks

2016-11-02 10:05 UTC, IgorKheidorov commented on Homework_11/src/testng/BicycleTest.java
> +    public void moveToNextPointTestTime() {
The same test name as on line 41 is not allowed, change the name

2016-11-02 10:06 UTC, IgorKheidorov commented on Homework_11/test.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Do not put on review such files in future

2016-11-02 10:13 UTC, IgorKheidorov reviewed
No tests to check distance calculation method, tests are not cover full functionality, too little number of  negative tests

2016-11-07 10:54 UTC, merged